---
title: "Insurance Parity Laws and Reducing Suicides: Replicating Lang (2013)"
subtitle: Daniel Ownby
output: pdf_document

date: "`r format(Sys.Date(),'%m/%d/%Y')`"
abstract: Over the past two decades, despite efforts from psychologists and mental health professionals alike, the United States has seen a steady growth of suicides despite nearly all other Western countries experiencing the contrary. Apart of this growth could be attributed to the lagging implementation of mental health care pairty. The Mental Health Parity Act of 1996 (MHPA) was critized during the turn of the century for not doing enough to restrict insurance companies ability to discrimate between treating bodily and mental injury. In this study, I attempt to replicate and build upon results from Lang (2013) using additional data, propensity score matching methods along with heterogenous difference in difference.
bibliography: references.bib
fontsize: 12pt
header-includes: \usepackage{setspace}\doublespacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
```

\newpage

## Introduction

According to 2019 Survey for Drug use and Health, it was estimated that at least 51.5 million adults in the United States had some sort of mental illness. In the same year, 13.1 million were estimated to have a serious mental illness that resulted in serious functional impairment or interferes with at least one or more major life activity. Only 65.5% of those 13.1 million received any sort of mental health treatment in the past year. According to the Center for Disease Control's WISQARS Leading Causes of Death Report, Suicides are the second leading cause of death amongst people aged 10-34 and the fourth from 35-44 in the United States. Suicide rates have gradually increased over the past two decades, starting with 10.5 per 100,000 people to 14.2 per 10,000 in 2018. Suicide rates vary from state to state with both east and west coasts supporting low rates such as 7.4 per 100,000 while mid-western states suffer from rates as high as 25 per 100,000. Several Sources outline the negative effects not only through statistical life projections and productivity losses but more generally how devastating the preventable loss of life has on communities. [@klick2006; @lang2013]

The Federal Mental Health Parity Act of 1996 prevented group health plan and insurance issuers from offering less mental health or substance abuse coverage benefits compared to regular medical coverage. If a provider gave mental health services, they couldn't offer benefit limitations that they wouldn't otherwise give to their same medical/surgical coverage. Most states by 2002 instated mental health parity laws alongside further stipulations with varying degrees of restrictiveness and exemptions.

### Lang (2013)

My seminal paper, @lang2013 attempts to identify causal effects using difference-in-difference methods and fixed effects using two policy shocks, the aftereffects of the Federal Health Parity Act of 1996 and The Affordable Care Act of 2008. @lang2013 showed a statistically significant effect of a 4-7% decrease in suicide rate after policy implementation. I draw the same data detailed in the study but add years spanning from 1990 to 2016, 36 years of data in total. I run my difference in difference using regression unlike @lang2013 addition to conduct propensity score matching methods to achieve a better balance between covariates between control and treatment states.

### Parity laws:

 Any state implementing a law that requires insurance packages to include access to mental health services and to have those services at parity with any other physical service is flagged as a parity state. This type of law is the strongest type amongst the ones implemented and is the type expected to create an effect this study investigates. A less strict version of the parity law is the "mandated offering" law, which does not force insurance package providers to provide mental health services in the first place. This can be a crucial difference when it comes to further analysis but for the purposes of this study both are lumped together as a Parity state.

## Literature

## Data

My dataset pulls from the same sources from @lang2013 with the exception of one variable.

## Methods

## Results

## Discussion

## Conclusion

## Figures

\newpage

```{=latex}
\begin{table}[!htbp] \centering \renewcommand*{\arraystretch}{1.1}\caption{Summary Statistics}\resizebox{\textwidth}{!}{
\begin{tabular}{lrrrrrrr}
\hline
\hline
Variable & N & Wt. Mean & Wt. SD & Min & Pctl. 25 & Pctl. 75 & Max \\ 
\hline
Suicide Rate & 765 & 11.32 & 2.681 & 4.021 & 10.59 & 13.98 & 24.97 \\ 
Log suicide rate & 765 & 2.398 & 0.2415 & 1.392 & 2.36 & 2.638 & 3.218 \\ 
Unemployment rate & 765 & 5.573 & 1.421 & 2.108 & 4.267 & 6.192 & 11.23 \\ 
Bankrupcy rate per 100k & 765 & 435.6 & 169.5 & 79.46 & 287.6 & 516.5 & 1117 \\ 
Percent of workers in large Firms & 765 & 0.483 & 0.03803 & 0.2699 & 0.4291 & 0.5025 & 0.5711\\ 
\hline
\hline
\end{tabular}
}
\end{table}
```
```{=latex}
\begin{table}[!htbp] \centering \renewcommand*{\arraystretch}{1.1}\caption{Summary Statistics}\resizebox{\textwidth}{!}{
\begin{tabular}{lrrrrrrrrr}
\hline
\hline
Pre\_Post\_Parity & \multicolumn{3}{c}{No-Parity} & \multicolumn{3}{c}{Post-Parity} & \multicolumn{3}{c}{Pre-Pairty}  \\ 
 Variable & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Wt. Mean} & \multicolumn{1}{c}{Wt. SD} & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Wt. Mean} & \multicolumn{1}{c}{Wt. SD} & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Wt. Mean} & \multicolumn{1}{c}{Wt. SD} \\ 
\hline
Suicide Rate & 330 & 12.57 & 2.263 & 178 & 9.848 & 2.583 & 257 & 10.85 & 2.548 \\ 
Log suicide rate & 330 & 2.517 & 0.1696 & 178 & 2.255 & 0.2545 & 257 & 2.356 & 0.2385 \\ 
Unemployment rate & 330 & 5.338 & 1.288 & 178 & 5.134 & 1.113 & 257 & 6.131 & 1.568 \\ 
Bankrupcy rate per 100k & 330 & 442.5 & 188.5 & 178 & 476.1 & 169.3 & 257 & 401.3 & 137.3 \\ 
Percent of workers in large Firms & 330 & 0.4887 & 0.03845 & 178 & 0.4886 & 0.03846 & 257 & 0.4727 & 0.03511\\ 
\hline
\hline
\end{tabular}
}
\end{table}
```
```{=latex}

\begin{table}


\caption{Weighted Means of Treated States, Pre and Post Period}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
TreatPrePostPeriod1998 & mean & st.err & sd & n\\
\midrule
Post-Period & 9.7867 & 0.2927 & 2.5778 & 203\\
Pre-Period & 11.9407 & 0.1484 & 2.4668 & 562\\
\bottomrule
\end{tabular}
\end{table}
```
```{=latex}
\begin{table}

\caption{Weighted Means of Non-Treated States, Pre and Post Period}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
NonTreatPrePostPeriod1998 & mean & st.err & sd & n\\
\midrule
NoTreatPost-Period & 12.2426 & 0.2118 & 2.0905 & 154\\
NoTreatPre-Period & 11.0899 & 0.1726 & 2.7634 & 611\\
\bottomrule
\end{tabular}
\end{table}
```
```{=latex}
\begin{table}

\caption{Weighted Mean Suicide Rates of Treated and Nontreated States, Pre and Post Period}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
TreatPrePostPeriod1998 & mean & st.err & sd & n\\
\midrule
NoTreatPost-Period & 12.2426 & 0.2118 & 2.0905 & 154\\
NoTreatPre-Period & 12.8921 & 0.2264 & 2.3786 & 176\\
Post-Period & 9.7867 & 0.2927 & 2.5778 & 203\\
Pre-Period & 11.0831 & 0.2616 & 2.4765 & 232\\
\bottomrule
\end{tabular}
\end{table}
```
```{=latex}
\begin{table}

\caption{Weighted Mean Log Suicide Rates of Treated and Nontreated States, Pre and Post Period}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
TreatPrePostPeriod1998 & mean & st.err & sd & n\\
\midrule
NoTreatPost-Period & 2.4915 & 0.0165 & 0.1625 & 154\\
NoTreatPre-Period & 2.5413 & 0.0165 & 0.1732 & 176\\
Post-Period & 2.2485 & 0.0288 & 0.2537 & 203\\
Pre-Period & 2.3800 & 0.0241 & 0.2285 & 232\\
\bottomrule
\end{tabular}
\end{table}
```
\newpage

## References
